language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4labscmf1985
  api_key:
    secure: bBq9h7fEqTBKKFfeFPPidcXcGdeEJ1bTrgvayBVysLHGGeGS4AEkq2fxqYbwrd2h40cSMcyd+r4ZfQ9lcjKd4tsurOOBABDXbfFvvk1X8C/BzEYQ0wgeel8PZHztNeDveJuGw0pVyevbsv6J4vMQ12FxFs3D8QaZIwvVIYuCqT/TXDudyqjZBcroNddCnVW41ShxvjvN+f/2AIl2zLv7BZ5y/z6hEo8Mq7ZUAaXzbKjYvjRey/FANay60Hd/3JMfXud4JjsxpKsS5DSex3IXVpdf603B6AAwjIl6ar0eJLPLZBzE+6j3E5GcO0Ohtbaoz0NUURxVFFWk3TlGSCIXA9NfQDTL9VbZqx88Y6i2KW/L4fOLM9fc5bQ25xBNJedyt9psJtgwC186vc5hT/1ddkOyziZFppSK+20zrLKIFs3RN+9Z2fFV5KboK0EUzE2myCuepkSnQKSQBUzkiBhVHsqS6aAIFoAtDG1U3KID1eSX1yPngFX2BTxyyZ+hGAKrFPqlx+WpZc2O+yt93ZVGQ42+MofCHI4XCqlC6tPP7CKYU6ZO8Vz75Lqlxu4T5WtQ4tyMb825Chso+Kni0ri8spGeoJmn97+d5iCVLuxpWcKK/pDPYNYNLB6H1tnrr57/MLtPKRZqTZUWEEA+0upZAaVJZTMxbEvd7s2+frejsDs=
